teams = Team.create([{name: "Boston Celtics"},
        {name: "Brooklyn Nets"},
        {name: "New York Knicks"},
        {name: "Philadelphia 76ers"},
        {name: "Toronto Rapters"},
        {name: "Chicago Bulls"},
        {name: "Cleveland Cavaliers"},
        {name: "Detroit Pistons"},
        {name: "Indiana Pacers"},
        {name: "Milwaukee Bucks"},
        {name: "Atlanta Hawks"},
        {name: "Charlotte Hornets"},
        {name: "Miami Heat"},
        {name: "Orlando Magic"},
        {name: "Washington Wizards"},
        {name: "Denver Nuggets"},
        {name: "Minnesota Timberwolves"},
        {name: "Oklahoma City Thunder"},
        {name: "Portland Trail Blazers"},
        {name: "Utah Jazz"},
        {name: "Golden State Warriors"},
        {name: "Los Angeles Clippers"},
        {name: "Los Angeles Lakers"},
        {name: "Phoenix Suns"},
        {name: "Sacramento Kings"},
        {name: "Dallas Mavericks"},
        {name: "Houston Rockets"},
        {name: "Memphis Grizzlies"},
        {name: "New Orleans Pelicans"},
        {name: "San Antonio Spurs"}
])
