# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 618b5faf9b44836115f3405baad085a2e237b55ef7b22c55f097196ec2d5c2018a14dc18593785a50772885706d97b7b5b74924f88b5964f30518f775db4df18

test:
  secret_key_base: c51e88c840588e1d9243651985637659aa196d0d4753f37cf562fcaf61b267d4f12151b6d29306c8c1276969c95d9e9e68219795057a8dd1288d10b1ca8d72f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
