# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c998909415c99651d5f290e62a9a9bf62b66e5e11fece7fe916ec9e8123b408a12f007475c101668acea5a4ddf894aba5554e0e4199bf4c7e7074a0bbde0325c

test:
  secret_key_base: 0dc1b641d6e34f4c969ba3ee4bcbcf8dc5a8e57ac848ee2bf834ebcec080347cc0e772d411f7e5c70c6c334b3373af75ab98df5c8133cc7dc18830bdbaf5acf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
